version: 1.10.{build}
branches:
  only:
  - master

install:
- ps: dotnet tool restore
- ps: dotnet restore --use-current-runtime
- ps: dotnet build --no-restore

build:
    project: LogExpert.sln

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  my_variable:
    secure: Qpq/4cyuTUzmt/r4HsQxioG6WXrZSK3mzVq5iUJC2RI=
  NugetApiKey:
    secure: wvIhRcMUX/CvZjPhzCk7fBowLUSFcILbfomGr+rl8iBv0sdBn4cAuv/CAHJda9BQ
  ChocolateyApiKey:
    secure: mXmzLqgFyDEjGRcE4UpqwqOXmdiCm9HwJ2V3LzSAz06GL1OaBDoTzidw7Rly+UHk
  GitHubApiKey:
    secure: N83nQZ/QQVqpRnl0D6F/xSbKjn062y07JdskpUpbWryMY2JDo4Be9lUXmob+xcOO

test: off
